config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:edit, :update, :new, :create, :show]
  resources :favorites, only: [:index, :create, :destroy]
  resources :pictures do
  collection do
    post :confirm
    end  
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

    private

    def login_required
      redirect_to new_session_path unless current_user
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites.all
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  def index
    @pictures = Picture.all.where.not(content: nil,image: nil)
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id 
    render :new if @picture.invalid?
  end

  def edit
    unless @picture.user_id == current_user.id
      redirect_to new_session_path
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if params[:back]
        render :new
      else
        if @picture.save
          format.html { redirect_to picture_url(@picture), notice: "写真が投稿されました" }
          format.json { render :show, status: :created, location: @picture }
          # NoticeMailer.notice_mail(@picture).deliver
        else
          render :new
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @picture.user_id == current_user.id
      @picture.destroy
      respond_to do |format|
      format.html { redirect_to pictures_url, notice: "写真を削除しました" }
      format.json { head :no_content }
    end
    
    else
      redirect_to new_session_path notice: "ログインを行なってください"
    end
  
  end

    private

    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:content, :image, :image_cache, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render :new
      end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to new_session_path
    end
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_path(user.id), notice: "ユーザー情報を編集しました！"
    else
      render :show
    end
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to user_path(user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation,
                                  :image, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new'|| action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= image_tag favorite.picture.image.url %></td>
    <td><%= favorite.picture.content %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to '投稿一覧画面に戻る', pictures_path %>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header>
    <div class="title">Instagram.clone</div>
    </header>

    <body>

    <div class="c_button">
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    </div>
    
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

  </body>

  <body>
    <%= yield %>
  </body>

  <footer>
  <div class="footer_text">
  created by WEF2205_SHUNSUKE_SATO
  </div>
  </footer>

</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url:choose_new_or_edit) do |form| %>

  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :user_id %>
  
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <p>コメント:<%= @picture.content %></p>
  <p>投稿者:<%= @picture.user.name %></p>
  
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>写真を編集する</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'この写真の投稿を確認する', @picture %> |
<%= link_to '写真一覧へ戻る', pictures_path %>

app/views/pictures/index.html.erb
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Image</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.content %></td>
        <td><%= image_tag picture.image.url %></td>
        <td><%= picture.user.name %></td>
        <td><%= link_to '詳細', picture %></td>
        
        <% if current_user.id == picture.user_id %>
          <td><%= link_to '編集', edit_picture_path(picture) %></td>
          <td><%= link_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
    <% end %>
  </tbody>
</table>

<br>

<div class="f_button">
<%= link_to '写真を投稿する', new_picture_path %>
<%= link_to 'お気に入り', favorites_path %>
</div>

<br>

app/views/pictures/new.html.erb
<h1>写真を投稿する</h1>

<%= render 'form', picture: @picture %>

<%= link_to '戻る', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"></p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @picture.user.name %>
</p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to '編集する', edit_picture_path(@picture) %> |
<%= link_to '戻る', pictures_path %>

app/views/users/edit.html.erb
<h1>ユーザー情報を編集する</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <% if current_user.id == @user.id %>
    <%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :imege %>
    <%= f.file_field :image %>

    <%= f.submit "編集" %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :imege %>
  <%= f.file_field :image %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<%= image_tag @user.image.url %>
<p>名前:<%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>


<p><%= link_to "プロフィールを編集する", edit_user_path(@user.id) %></p>

<p><%= link_to "投稿一覧ページ", pictures_path %></p>